ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: |
      pip3 install -U -r requirements.txt --user
      apt-get install -y python3-tk ghostscript
      pip install "camelot-py[cv]"

